### ISSUE TITLE
Should we adopt the available cookbooks in supermarket?

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#2] opened 2015-05-10 22:04 UTC
There's quite a few cookbooks here:
https://supermarket.chef.io/available_for_adoption

Should we adopt all of them? Any of them? How should we decide about this sort of thing in the future?

**Comment by miketheman** [comment] 2015-05-10 22:41
I think it behooves the brigade to figure out an adoption-maintainership process - what it means, how it's delegated/moved/transferred, and what the expectation is once it's handled by the brigade.

I also see the Brigade as a potential clearing house to help the transfer of cookbook to maintainers that desire the responsibility.

**Comment by josephholsten** [comment] 2015-05-10 23:24
I'm a fan of the [hapi.js model](http://hapijs.com/governance).

> Each repository is assigned a lead maintainer. Lead maintainers act as the repository's BDFL (benevolent dictator for life) [...]
> 
> Lead maintainers cannot be removed unless they leave, assign their position to someone else, or have become inactive for 30 days and fails to respond to attempts to communicate, at which point a new contributor will assume responsibility for the repository.

I think of the brigade's core mission is to Ensure Cookbooks Are Maintained. Quality, consistency, resource-centricness, &c are lower priority.

**Comment by zarry** [comment] 2015-05-11 21:00
I can get behind the hapi.js model although that may not always work best given some users available time.  Agree with the core mission with the exception that we have a certain standard of quality and consistency we choose to uphold as the chef-brigade.  

My initial thought is to not adopt anything but the mongo cookbook.  Lets get that up to a level we all feel comfortable with as a chef-brigade managed cookbook and then we can choose our adoption path.  I don't want us to try and tackle the world on our first go around and end up with a bunch of half maintained cookbooks because we bit off a bit more than we could chew at the time.

**Comment by dblessing** [comment] 2015-05-11 22:18
@josephholsten I like the model you describe. Assign a lead maintainer(s) to each project and mostly let them run that show within that project. It might be nice to have a CoC in the Chef Brigade to ensure the maintainers are being good but other than that too much structure might cause maintainers to not want to stay around.

It would be good to iron out some of these details before taking in other projects. It might be helpful to ensure a lead maintainer is assigned before adopting the project, too. No sense in promising to maintain the project with no clear leader.

**Comment by luishdez** [comment] 2015-05-12 03:45
I agree with @zarry we should get comfortable with the management of a few repos in order to clarify the collaboration process. Let's start with mongo and see what happens…

**Comment by bkconrad** [comment] 2015-05-12 03:49
+1, better to get the process solid on one project and expand than to overreach and have to restructure.

Then again, there might be some selection bias at work here :)

**Comment by luishdez** [comment] 2015-05-12 06:01
Recently I saw the Symfony2 workflow for the community and it's interesting too.  I like it more than an strict BDFL model.

![13734902144_74d38cc6d1_o](https://cloud.githubusercontent.com/assets/38347/7580905/fa86915a-f87c-11e4-9680-48f84f3573c5.png)

**Comment by zarry** [comment] 2015-05-12 13:46
@luishdez That is an interesting model laid out by Symfony2 and in the end might be a bit more forgiving of a single users time and keep the cookbook progressing even when the sole owner is unavailable. 

I could get behind trying something like Symfony2 has outlined.

**Comment by dblessing** [comment] 2015-05-12 14:38
I don't see an issue with having multiple maintainers. The trick is finding multiple people interested and willing. Having one maintainer will be just fine in most cases - these are small cookbooks not large, monolithic projects. The beauty of a larger effort like Chef Brigade is that cookbooks will be under this org and as such will always have other authorized collaborators that can step in when necessary. If we attempt something like Symphony2 we may add too much overhead.

**Comment by luishdez** [comment] 2015-05-12 15:22
It doesn't have to be strict. But I think that just the basic definition of the roles helps a lot in the maintenance of a project. In my company we mess up things even with 3 people in samll projects when we don't define our roles. People doesn't know what to do or no to do, or feel afraid to do things. Eg: Right now I was planning to tag the mongo PRs but I'm not sure if someone has other ideas … well  you know my point.

EG: The Symfony2 idea applied to mongodb will be something like:
- Leader: Someone to organize the issues, solve quick issues, PRs and try to keep things moving, contact of mergers to get feedback etc. 
- Mergers: 3-4 collaborators that have a good knowledge about the repo. Almost same as leader but they can focus more on merge complex PRs, other quick fixes too, but they know that there is someone (leader) trying to organizing the repo
- Decision makers: ( the rest of the team? ) They provide a "valuable" feedback to new features, changes etc…

**Comment by dblessing** [comment] 2015-05-12 15:39
I agree some structure and direction is helpful. The definitions you have above seem fine. Assigning a single maintainer/leader up front will allow that person to begin maintenance on the cookbook and then 'promote' other people as they express interest. No need to assign multiple 'mergers' up front or it just delays the actual work getting done in the short term IMO. Definitions would be in place though when that opportunity arises.

**Comment by lamont-granquist** [comment] 2015-07-10 21:08
Expanding on my comments in https://github.com/chef-brigade/meta/issues/6#issuecomment-120523879 I think this decision should be easy.  Right now you need lots of people with commit and merge rights and need as friction-free of a way to get the most people able to manage the most number of community cookbooks.  So the first model will be best, and you should just slurp in redguide and everyone else you can sign up.

You don't yet have the problems that would require "mergers" and "decision makers" and "leaders" and such.  That only needs to happen when you start seeing more satellite members of the group making bad merges and causing regressions and actual problems and really need to start worrying about the quality of individual contributions.  Right now you need to just get more contributions and get work happening.  If you immediately throw a lot of bureaucracy and process into this right out of the gate then you'll wind up slowing down your velocity and people will drop out when they can't get the various deciders to pay attention to their issues.

**Comment by josephholsten** [comment] 2015-07-14 17:22
is there anything further we need to decide about this issue? Could anyone with outstanding opinions wrap their changes into a PR modifying [`membership.md`](https://github.com/chef-brigade/meta/blob/master/membership.md)? I'll close this in a couple days if there are no further changes to be made.

**Comment by lamont-granquist** [comment] 2015-07-14 17:39
On the original topic, and not the diversion, I think you probably should just let any member of the group adopt cookbooks they want to maintain.  But someone should probably have an itch to scratch about the cookbook before bringing it into the group.  Otherwise you'll just create unfunded mandates to manage a bunch of cookbooks that maybe nobody in the group has any interest in.  I feel that a policy like that will create just enough focus while keeping it reasonably friction-free and avoiding immediately creating a lot of unmanaged cookbooks within this group and a large debt burden that nobody is working on.

Having anyone able to pull in any cookbook that gives them an itch might create a bit of chaos and unmanaged cookbooks down the road, but I think it'll let the group start doing work and being productive without a lot of centralized leadership which is going to be better for kicking it off.  Later the list of cookbooks might need to be groomed and some dropped by this group, and we might need some filtering of which cookbooks are accepted, but that's all future bridges to be crossed.  The problem right now is to pull in some cookbooks and start some work.

**Comment by dblessing** [comment] 2015-07-14 18:39
@lamont-granquist :+1:

**Comment by rex** [comment] 2015-07-14 18:42
@lamont-granquist :+1:

**Comment by josephholsten** [comment] 2015-07-15 17:26
@lamont-granquist :+1: to not creating unfunded mandates.

Anyone want to write this up?

**Comment by tas50** [comment] 2016-12-09 17:28
I'm a big 👎  on this. If someone wants a cookbook and they want to maintain it they should pull it in. We shouldn't just blanket adopt though.

**Comment by damacus** [comment] 2016-12-09 17:34
👎 
If someone wants to pull it into sous-chefs that's great. But they really should have skin in the game to maintain it, otherwise it'll just be another set of cookbooks that no one wants to maintain.

**Closed as completed** 2016-12-09 17:37 UTC
