### ISSUE TITLE
Naming convention for supermarket

### ISSUE THREAD

**Issue by luishdez** [sous-chefs/meta#3] opened 2015-05-27 01:10 UTC
We've adopted the mongodb cookbook that uses "mongodb" as namespace in chef supermarket. Our repo name conflicts with the old one. We need to set a new name for the supermarket.

I think we should define a naming convention for this purpose.

I would go with brigade-mongodb and follow the pattern brigade-{name} Using brigade as namespace for other cookbooks 

Eg: 
- Github: nginx-cookbook  Supermarket: brigade-nginx
- Github: varnish-cookbook Supermarket: brigade-varnish

Similar as grunt-contrib, This will prevent any conflict with other cookbooks

Any thoughts?

**Comment by thomas-riccardi** [comment] 2015-05-27 09:06
:+1:

**Comment by josephholsten** [comment] 2015-06-01 13:37
honestly, I'd rather our mongodb replaced the existing mongodb cookbook. I'll bug @jamesonjlee to see if he can get us added to the existing one.

For situations where we can't get the un-namespaced spot, :+1: to brigade-foo

**Comment by luishdez** [comment] 2015-06-04 12:57
Ok @josephholsten  let's give it some time to see if we can get the original name :+1:

**Comment by luishdez** [comment] 2015-06-18 21:52
@josephholsten Do we have any news ?

**Comment by josephholsten** [comment] 2015-07-14 02:26
@luishdez sorry, I heard back from @jamesonjlee and he doesn't have access. I'll bug @thekorn and @edelight. Until then, let's proceed with `brigade-mongodb`.

**Comment by zuazo** [comment] 2015-07-14 14:26
I think it would be better to use an underscore in the prefix: `brigade_`. For example `brigade_mongodb`.

I propose this because using dashes gives problems when making ChefSpec tests: https://github.com/sethvargo/chefspec#testing-lwrps

> WARNING Cookbooks with dashes (hyphens) are difficult to test with ChefSpec because of how Chef classifies objects. We recommend naming cookbooks with underscores (_) instead of dashes (-).

**Comment by josephholsten** [comment] 2015-07-14 17:24
@zuazo and that's why I'm glad to have a community of smart folks about.

**Comment by rex** [comment] 2015-07-15 04:21
Indeed. @zuazo great catch. I prefer to have hyphens instead of underscores in repository names, but for consistency's sake underscores are perfectly fine IMO. I also like the `brigade_<package>` convention. Simple, sexy.

**Comment by josephholsten** [comment] 2015-07-16 02:38
Could someone start a recommendations doc? I've started a template in https://github.com/chef-brigade/cookbook-skeleton, but that's not really where we want guidance for this sort of thing.

**Comment by luishdez** [comment] 2015-07-21 02:55
Mmmm… I do prefer dashes as well, actually I kinda hate underscores :smile: 

I haven't use chefSpec that much so I can't tell, but are we using chef spec in all the repos? If this causes a problem that can not be avoided with good coding style practices I'm fine then.

It's not the most important thing but I think that naming is not trivial 

For example with underscores the name is treated as a one word for SEO purposes. In the title h1 and URLs that gives good hints for SEO… If someone searches for `mongo cookbook` those keywords won't match, This name is shown in H1, URls, texts… in pages like github, supermarket among others. 

Though there is no much competition so it's not a big problem… but I think the "{resource}-cookbook" pattern is the best approach for this.

**Comment by dblessing** [comment] 2015-07-21 03:00
ChefSpec is an essential tool IMO. Can you name the cookbook with an underscore and still name the repo with a dash, use alternative characters in the README, etc. to get around SEO issues?

**Comment by lamont-granquist** [comment] 2016-12-08 21:22
Dashes are a bad option for any ruby code:

```ruby
% pry
[1] pry(main)> def foo-bar(thing)
SyntaxError: unexpected '-', expecting ';' or '\n'
def foo-bar(thing)
        ^
[1] pry(main)> def foo_bar(thing)
[1] pry(main)* end
=> :foo_bar
```

We've generally stamped out all those bugs that we know of, but its still considered best practice to use underscores instead of dashes in cookbooks to avoid any future issues.

The issue is not confined to chefspec.  Its just a best practice recommended by nearly everyone who has touched chef-client core.

**Comment by lamont-granquist** [comment] 2016-12-08 21:25
also if you're really adopting the mongodb cookbook it should still be named mongodb so users can still find it and upgrade and don't have to update all their dependencies.

you only need to do this when you're forking an existing cookbook, and can't adopt the cookbook from the original author.

**Comment by zuazo** [comment] 2016-12-08 21:43
@lamont-granquist AFAIK we have no permissions over the original `mongodb` cookbook in supermarket. See https://github.com/sous-chefs/mongodb/pull/106 for more information.

**Comment by damacus** [comment] 2016-12-09 17:21
Do we think this is covered by https://github.com/sous-chefs/meta/blob/master/forking.md ?

**Comment by damacus** [comment] 2016-12-09 17:44
Closing as per slack discussion on #sous-chefs

**Closed as completed by damacus** 2016-12-09 17:44 UTC
